spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /templates
      suffix: .html
    pathpattern:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1080514658625-hrihjje4km1cplghrbnt9ukb2n3mkg1g.apps.googleusercontent.com
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mariadb://localhost:3306/btdoctor
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect

application:
  name: Biotekna Doctor
  client:
    domain: http://localhost:3000
  security:
    jwt:
      secret-key: 6150645367566B58703273357638792F423F4528482B4D6251655468576D5A71
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days
      registration-token:
        expiration: 864000000 # 10 days
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
  email:
    host: ${EMAIL_HOST}
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    debug: false
    no-reply: noreply@biotekna.com
  support:
    phone: 1234567890
    email: support@doctor.biotekna.com