package com.bsf.security.exception._common;

public enum BTExceptionName {
    AUTH_REGISTRATION_DUPLICATE_USERNAME_ACCOUNT,
    AUTH_REGISTRATION_PASSWORDS_DO_NOT_MATCH,
    ACCOUNT_NOT_FOUND,
    INVALID_EMAIL,
    EMAIL_CAN_NOT_BE_EMPTY,
    PASSWORD_CAN_NOT_BE_EMPTY,
    FIRST_NAME_CAN_NOT_BE_EMPTY,
    LAST_NAME_CAN_NOT_BE_EMPTY,
    CURRENT_PASSWORD_DO_NOT_MATCH
}
